routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
})->name('home');*/

Route::get('/','PublicPageController@index')->name('home');

Route::get('product/{category_slug}','PublicPageController@SubCatList')->name('category.page');

Route::get('products/{category_slug}','PublicPageController@landingPage')->name('landing.page');

Route::get('product/{category_slug}/{sub_category_slug}','PublicPageController@showSubCat')->name('subcat.page');

Route::get('product/{category_slug}/{sub_category_slug}/total-cover','PublicPageController@totalCover')->name('totalcover.page');


//Route::get('/food-beverages/{subcategory_id}','PublicPageController@foodAndBeverages')->name('foodbeverages.page');

Route::get('hospitality','PublicPageController@hospitalityPage')->name('hospitality.page');

/*Route::get('/foodandproductrange','PublicPageController@foodAndProductRange')->name('foodandproductrange.page');*/



Route::get('product/{category_slug}/{sub_category_slug}/product-range','PublicPageController@productRange')->name('productrange.page');

Route::get('product/{category_slug}/{sub_category_slug}/equipment','PublicPageController@showEquipment')->name('equipment.page');

Route::get('product/{category_slug}/{sub_category_slug}/services','PublicPageController@showServices')->name('showServices.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training','PublicPageController@safetyTraining')->name('safety-training.page');

Route::get('product/{category_slug}/{sub_category_slug}/{product_range_slug}/productsds','PublicPageController@productSdsItems')->name('productsds.page');

Route::get('product/{category_slug}/{sub_category_slug}/{product_range_slug}/productsds/{product_slug}','PublicPageController@productInfo')->name('productInfo.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/chemical-training-safety','PublicPageController@chemicalTrainingSafety')->name('chemicaltrainingsafety.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/new-safety-initiatives','PublicPageController@newSafetyInitiatives')->name('newsafetyinitiatives.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/new-label','PublicPageController@newLabel')->name('newlabel.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/safety-and-operational-charts','PublicPageController@safetyOpCharts')->name('safetyOpCharts.page');

//Route::get('news','PublicPageController@newsPage')->name('news.page');

Route::get('contactus','PublicPageController@contactUsPage')->name('contactus.page');

//Route::get('aboutus','PublicPageController@aboutUsPage')->name('aboutus.page');
//
//Route::get('aboutus/ourvalues','PublicPageController@ourvaluesPage')->name('ourvalues.page');
//
//Route::get('aboutus/company-profile','PublicPageController@companyProfilePage')->name('company-profile.page');

Route::get('ourstory','PublicPageController@ourstoryPage')->name('ourstory.page');

Route::get('cleansafe-industrial-dispensing','PublicPageController@cleanSafeIndustrialPage')->name('cleansafe.page');

Route::get('services','PublicPageController@servicesPage')->name('services.page');

Route::get('service-report','PublicPageController@serviceReport')->name('servicesreport.page');





Route::get('search','PublicPageController@searchProduct')->name('searchProduct.page');


Route::get('/productinfopdf','ProductController@productInfoPdf')->name('productinfo.pdf');
//login
//Auth::routes();
/*Route::get('/home', 'HomeController@index')->name('home');*/


//Dashboard

Route::group(['prefix' => 'admin'], function() {


    Route::group(['middleware' => ['auth']], function() {

        Route::get('/','DashboardController@index');

        Route::get('/logout','LoginController@destroy')->name('logout.user');

        Route::resource('/dashboard','DashboardController');

        Route::resource('/pages','PageController');

        Route::resource('/categories','ProductCategoryController');

        Route::resource('/subcategories','ProductSubCategoryController');

        Route::resource('/productrange','ProductRangeController');

        Route::any('/productrange/index/productrangeData','ProductRangeController@productrangeData')->name('productrange.get');

        Route::resource('/products','ProductController');

        Route::any('/products/index/productsData','ProductController@productData')->name('products.get');

        Route::any('/products/index/deleteFile','ProductController@deleteImgDetails')->name('deleteFile.get');

    });

    Route::group(['middleware' => ['guest']], function() {

        Route::post('/login','Auth\LoginController@login');
        Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
        Route::post('/register','Auth\RegisterController@register');
        Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('register');

        //logout

    });

});

app/ProductRange.php
<?php

namespace App;

use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;
use Illuminate\Database\Eloquent\Model;

use DataTables;
use Image;
use Illuminate\Support\Facades\URL;

use Illuminate\Support\Facades\File;

use Illuminate\Support\Facades\Input;

class ProductRange extends Model
{

    use HasSlug;

    public $incrementing = false;

    protected $table = 'product_range';

    protected $fillable = [
        'id','product_range_name', 'product_range_description','product_range_img','sub_product_category_id','product_range_slug'
    ];

    public function productSubCategory(){
        return $this->belongsTo('App\ProductSubCategory','sub_product_category_id');
    }

    public function getSlugOptions() : SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('product_range_name')
            ->saveSlugsTo('product_range_slug');
    }

    public static function storeProductRange($request){

        $product_range = new ProductRange();
        $product_range->id = uniqid();
        $product_range->product_range_name = $request->input('product_range_name');
        $product_range->product_range_description = $request->input('product_range_description');
        if($request->hasFile('product_range_img')){

            $image = $request->file('product_range_img');

            $filename = $product_range->id.'_'.time().'.'.$image->getClientOriginalExtension();

            $destinationPath = public_path('/uploads/product-range-images/'.$filename);

            Image::make($image)->resize(120,null,function ($constraint) {
                $constraint->aspectRatio();
            })->save($destinationPath);

            $product_range->product_range_img = $filename;
        }
        $product_range->sub_product_category_id = $request->input('sub_product_category_id');
        $product_range->save();

        return true;
    }

    public static function updateProductRange($request,$id){

        $product_range = ProductRange::find($id);
        $product_range->product_range_name = $request->input('product_range_name');
        $product_range->product_range_description = $request->input('product_range_description');

        if($request->hasFile('product_range_img')){

            $image = $request->file('product_range_img');

            $filename = $id.'_'.time().'.'.$image->getClientOriginalExtension();

            $destinationPath = public_path('/uploads/product-range-images/'.$filename);

            Image::make($image)->resize(120,null,function ($constraint) {
                $constraint->aspectRatio();
            })->save($destinationPath);

            $oldImgFile = $product_range->product_range_img;

            $product_range->product_range_img = $filename;

            File::delete(public_path('/uploads/product-range-images/'.$oldImgFile));

        }
        $product_range->sub_product_category_id = $request->input('sub_product_category_id');
        $product_range->save();

        return true;
    }

    public static function allProductRange($request){

        $product_range = ProductRange::with('productSubCategory');

        return DataTables::eloquent($product_range)

            ->addColumn('action', function ($product_range) {

                    $btn_html = '<a href="'.route('productrange.edit',$product_range->id).'" class="btn btn-info">Edit</a> ';
                    $btn_html .= '| <a href="#delete-modal" data-toggle="modal" data-product_range_id="'.$product_range->id.'" class="btn btn-danger">Delete</a>';
                return $btn_html;
            })
            ->editColumn('created_at', function ($product_range) {
                $newDate = date('m-d-Y', strtotime($product_range->created_at));
                return $newDate;
            })
            ->editColumn('productSubCategory.sub_cat_name', function ($product_range) {
                $sub_category_name = $product_range->productSubCategory->sub_cat_name;
                return $sub_category_name;
            })
            ->toJson();
    }

}

app/Http/Controllers/ProductRangeController.php
<?php

namespace App\Http\Controllers;

use App\ProductSubCategory;

use Illuminate\Http\Request;

use App\Http\Requests\CreateProductRange;

use App\ProductRange;

use Toastr;

use App\Product;

class ProductRangeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$product_range = ProductRange::all();
        return view('cms.productrange.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function productRangeData (Request $request){

        $product_range = ProductRange::allProductRange($request);
        return $product_range;
    }


    public function create()
    {
        //$categories = [''=>''] + Category::lists('name', 'id')->all();
        $sub_category = ProductSubCategory::orderBy('sub_cat_name','asc')->pluck('sub_cat_name', 'id')->all();

        return view('cms.productrange.create')->with(compact('sub_category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateProductRange $request)
    {
        $product_range = ProductRange::storeProductRange($request);

        Toastr::success('Product range successfully created!', 'Success', ["positionClass" => "toast-top-right"]);

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product_range = ProductRange::find($id);
        $sub_category = ProductSubCategory::orderBy('sub_cat_name','asc')->pluck('sub_cat_name', 'id')->all();

        return view('cms.productrange.edit')->with(compact('product_range','sub_category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateProductRange $request, $id)
    {
        $product_range = ProductRange::updateProductRange($request,$id);

        Toastr::success('Product range successfully updated!', 'Success', ["positionClass" => "toast-top-right"]);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $productRange = ProductRange::find($id);

        $productRange->forceDelete();

        $product = Product::where('product_range_id','=',$productRange->id);

        $product->delete();

        Toastr::error('Product Range successfully deleted!', 'Deleted', ["positionClass" => "toast-top-right"]);

        return redirect()->back();
    }
}

resources/views/cms/productrange/create.blade.php
@extends('cms.layouts.master')

@section('page_css')
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">

                    <div class="col-lg-12">
                        <h1 class="page-header">Create Product Range</h1>
                    </div>
            </h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    @include('cms.productrange.form')
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')

@endsection

@section('page_js')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CreateProductRange','#product-range-form') !!}

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    {!! Toastr::message() !!}
@endsection

resources/views/cms/productrange/edit.blade.php
@extends('cms.layouts.master')

@section('page_css')
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">Edit Product Range</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    @include('cms.productrange.form')
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')

@endsection

@section('page_js')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CreateProductRange','#product-range-form') !!}

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    {!! Toastr::message() !!}
@endsection

resources/views/cms/productrange/form.blade.php
@if(isset($product_range))
    {{ Form::model($product_range, ['route' => ['productrange.update', $product_range->id], 'method' => 'put','id'=>'product-range-form','files'=>'true']) }}
@else
    {{ Form::open(['route' => 'productrange.store','id'=>'product-range-form','files'=>'true']) }}
@endif

<div class="form-group  {{ $errors->has('product_range_img') ? 'has-error' : '' }}">
    {{Form::label('product_range_img', 'Product image')}}
    {{ Form::file('product_range_img', old('product_range_img'),['class' => 'form-control']) }}
    {!! $errors->first('product_range_img', '<p class="help-block">:message</p>') !!}
</div>

@if(isset($product_range))
    <div class="col-md-12">
        <div class="row">
            <img src="{{($product_range->product_range_img == '' ) ? asset('uploads/product-range-images/blank.png') : asset('uploads/product-range-images/'.$product_range->product_range_img)}}" width="120px" >
        </div>
    </div>

    <div class="col-md-12">
        <div class="row">
            <label class="" for="description">Current image</label>
        </div>
    </div>
@endif

<div class="form-group  {{ $errors->has('sub_cat_name') ? 'has-error' : '' }}">
    {{Form::label('product_range_name', 'Name')}}
    {{ Form::text('product_range_name', old('product_range_name'),['class' => 'form-control','placeholder'=>'input product range name']) }}
    {!! $errors->first('product_range_name', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {{ $errors->has('product_range_description') ? 'has-error' : '' }}">
    {{Form::label('product_range_description', 'Description')}}
    {{ Form::textarea('product_range_description', old('product_range_description'),['class' => 'form-control','placeholder'=>'input description']) }}
    {!! $errors->first('product_range_description', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {{ $errors->has('sub_product_category_id') ? 'has-error' : '' }}">
    {{Form::label('sub_product_category_id', 'Select sub category')}}
    {{Form::select('sub_product_category_id', $sub_category, null, ['class'=>'form-control','placeholder' => 'choose one'])}}
    {!! $errors->first('sub_product_category_id', '<p class="help-block">:message</p>') !!}
</div>

{{ Form::submit('Save', ['class'=>'btn btn-primary']) }}

{{ Form::close() }}

resources/views/cms/productrange/index.blade.php
@extends('cms.layouts.master')

@section('page_css')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">Product Range
                {{--<a class="btn btn-primary" href="{{route('productrange.create')}}"><i class="fa fa-plus"></i> Add product range</a>--}}
            </h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Product range data
                </div>

                <div class="panel-body">
                    <table class="table table-bordered" id="product_range_table">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Sub category</th>
                            <th>Created at</th>
                            <th>Options</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                    {{-- {{ $product_sub_category->links() }}--}}
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')
    @include('cms.modal.delete-modal')
@endsection

@section('page_js')
    <!-- Datatable Js -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap.min.js"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    {!! Toastr::message() !!}

    <script type="text/javascript">

        $(document).ready(function ($) {


            var productRangeTable;

            productRangeData();


            $('#delete-modal').on('show.bs.modal', function (event) {

                var button = $(event.relatedTarget); // Button that triggered the modal
                var product_range_id = button.data('product_range_id'); // Extract info from data-* attributes

                var modal = $(this);

                var url = '{{ route("productrange.destroy", ":product_range_id") }}';
                url = url.replace(':product_range_id', product_range_id);
                $('#delete-form').attr('action',url);
            });


        });

        function productRangeData(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            productRangeTable = $('#product_range_table').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax:{
                    "url": "{!! route('productrange.get') !!}",
                    "type": "POST",
                },
                columns: [
                    { data: 'product_range_name', name: 'product_range_name' },
                    { data: 'product_range_description', name: 'product_range_description' },
                    { data: 'productSubCategory.sub_cat_name', name: 'productSubCategory.sub_cat_name'},
                    { data: 'created_at', name: 'created_at'},
                    { data: 'action', name: 'action' },

                ],
                columnDefs: [
                    { searchable: true, targets: '_all'},
                    { searchable: false, targets: [0,4]},
                    { orderable: false, targets: [0,4]},

                ],
            });
        }

    </script>

@endsection