routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
})->name('home');*/

Route::get('/','PublicPageController@index')->name('home');

Route::get('product/{category_slug}','PublicPageController@SubCatList')->name('category.page');

Route::get('products/{category_slug}','PublicPageController@landingPage')->name('landing.page');

Route::get('product/{category_slug}/{sub_category_slug}','PublicPageController@showSubCat')->name('subcat.page');

Route::get('product/{category_slug}/{sub_category_slug}/total-cover','PublicPageController@totalCover')->name('totalcover.page');


//Route::get('/food-beverages/{subcategory_id}','PublicPageController@foodAndBeverages')->name('foodbeverages.page');

Route::get('hospitality','PublicPageController@hospitalityPage')->name('hospitality.page');

/*Route::get('/foodandproductrange','PublicPageController@foodAndProductRange')->name('foodandproductrange.page');*/



Route::get('product/{category_slug}/{sub_category_slug}/product-range','PublicPageController@productRange')->name('productrange.page');

Route::get('product/{category_slug}/{sub_category_slug}/equipment','PublicPageController@showEquipment')->name('equipment.page');

Route::get('product/{category_slug}/{sub_category_slug}/services','PublicPageController@showServices')->name('showServices.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training','PublicPageController@safetyTraining')->name('safety-training.page');

Route::get('product/{category_slug}/{sub_category_slug}/{product_range_slug}/productsds','PublicPageController@productSdsItems')->name('productsds.page');

Route::get('product/{category_slug}/{sub_category_slug}/{product_range_slug}/productsds/{product_slug}','PublicPageController@productInfo')->name('productInfo.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/chemical-training-safety','PublicPageController@chemicalTrainingSafety')->name('chemicaltrainingsafety.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/new-safety-initiatives','PublicPageController@newSafetyInitiatives')->name('newsafetyinitiatives.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/new-label','PublicPageController@newLabel')->name('newlabel.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/safety-and-operational-charts','PublicPageController@safetyOpCharts')->name('safetyOpCharts.page');

//Route::get('news','PublicPageController@newsPage')->name('news.page');

Route::get('contactus','PublicPageController@contactUsPage')->name('contactus.page');

//Route::get('aboutus','PublicPageController@aboutUsPage')->name('aboutus.page');
//
//Route::get('aboutus/ourvalues','PublicPageController@ourvaluesPage')->name('ourvalues.page');
//
//Route::get('aboutus/company-profile','PublicPageController@companyProfilePage')->name('company-profile.page');

Route::get('ourstory','PublicPageController@ourstoryPage')->name('ourstory.page');

Route::get('cleansafe-industrial-dispensing','PublicPageController@cleanSafeIndustrialPage')->name('cleansafe.page');

Route::get('services','PublicPageController@servicesPage')->name('services.page');

Route::get('service-report','PublicPageController@serviceReport')->name('servicesreport.page');





Route::get('search','PublicPageController@searchProduct')->name('searchProduct.page');


Route::get('/productinfopdf','ProductController@productInfoPdf')->name('productinfo.pdf');
//login
//Auth::routes();
/*Route::get('/home', 'HomeController@index')->name('home');*/


//Dashboard

Route::group(['prefix' => 'admin'], function() {


    Route::group(['middleware' => ['auth']], function() {

        Route::get('/','DashboardController@index');

        Route::get('/logout','LoginController@destroy')->name('logout.user');

        Route::resource('/dashboard','DashboardController');

        Route::resource('/pages','PageController');

        Route::resource('/categories','ProductCategoryController');

        Route::resource('/subcategories','ProductSubCategoryController');

        Route::resource('/productrange','ProductRangeController');

        Route::any('/productrange/index/productrangeData','ProductRangeController@productrangeData')->name('productrange.get');

        Route::resource('/products','ProductController');

        Route::any('/products/index/productsData','ProductController@productData')->name('products.get');

        Route::any('/products/index/deleteFile','ProductController@deleteImgDetails')->name('deleteFile.get');

    });

    Route::group(['middleware' => ['guest']], function() {

        Route::post('/login','Auth\LoginController@login');
        Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
        Route::post('/register','Auth\RegisterController@register');
        Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('register');

        //logout

    });

});

resources/views/cms/pages/create.blade.php
@extends('cms.layouts.master')

@section('page_css')
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">Create page</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="{{route('pages.create')}}" method="post" role="form" id="page-create-form">
                        {{ csrf_field() }}
                        <div class="form-group  {{ $errors->has('page_name') ? 'has-error' : '' }}">
                            <label for="">Page name</label>
                            <input type="text" class="form-control" name="page_name"  id=""  value="{{ old('page_name') }}" placeholder="Input page name">
                            {!! $errors->first('page_name', '<p class="help-block">:message</p>') !!}
                        </div>

                        <div class="form-group {{ $errors->has('page_content') ? 'has-error' : '' }}">
                            <label for="">Page Content</label>
                            <textarea type="text" class="form-control" name="page_content" id="description" value="{{ old('page_content') }}" placeholder="Input page content" style="resize:vertical;
height:200px;
min-height:200px;
max-height:200px;"></textarea>
                            {!! $errors->first('page_content', '<p class="help-block">:message</p>') !!}
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')

@endsection

@section('page_js')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CreatePageRequest','#page-create-form') !!}

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    {!! Toastr::message() !!}
@endsection

resources/views/cms/pages/edit.blade.php
@extends('cms.layouts.master')

@section('page_css')
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">Edit page</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form action="{{route('pages.update',$page->id)}}" method="post" role="form" id="page-update-form">
                        {{ csrf_field() }}
                        <div class="form-group  {{ $errors->has('page_name') ? 'has-error' : '' }}">
                            <label for="">Page name</label>
                            <input type="text" class="form-control" name="page_name"  id=""  value="{{ $page->page_name }}" placeholder="Input page name">
                            {!! $errors->first('page_name', '<p class="help-block">:message</p>') !!}
                            <input name="_method" type="hidden" value="PUT"/>
                        </div>

                        <div class="form-group {{ $errors->has('page_content') ? 'has-error' : '' }}">
                            <label for="">Page Content</label>
                            <textarea type="text" class="form-control" name="page_content" id="description" placeholder="Input page content" style="resize:vertical;
height:200px;
min-height:200px;
max-height:200px;">{{ $page->page_content }}
                            </textarea>
                            {!! $errors->first('page_content', '<p class="help-block">:message</p>') !!}
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>

                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')

@endsection

@section('page_js')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CreatePageRequest','#page-update-form') !!}

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    {!! Toastr::message() !!}
@endsection

resources/views/cms/pages/index.blade.php
@extends('cms.layouts.master')

@section('page_css')

@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">Product Pages
                {{--<a class="btn btn-primary" href="pages/create"><i class="fa fa-plus"></i> Add page</a>--}}
            </h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Page data
                    </div>

                    <div class="panel-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>Page name</th>
                                <th>Page for</th>
                                <th>Created at</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($productcategory as $page)
                                <tr>
                                    <td>{{$page->page->page_name}}</td>
                                    <td>{{$page->category_name}}</td>
                                    <td>{{Carbon\Carbon::parse($page->page->created_at)->format('d/m/Y')}}</td>
                                    <td>
                                        <a href="{{route('pages.edit',$page->id)}}" class="btn btn-info" role="button">Edit</a>
                                       {{-- <a href="#" class="btn btn-danger" role="button">Delete</a>--}}
                                    </td>
                                </tr>
                            @empty
                                no page available
                            @endforelse
                            </tbody>
                        </table>
                        {{ $productcategory->links() }}
                    </div>
                    <!-- /.panel-body -->
                </div>
            <!-- /.panel -->

        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')

@endsection

@section('page_js')

@endsection