routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
})->name('home');*/

Route::get('/','PublicPageController@index')->name('home');

Route::get('product/{category_slug}','PublicPageController@SubCatList')->name('category.page');

Route::get('products/{category_slug}','PublicPageController@landingPage')->name('landing.page');

Route::get('product/{category_slug}/{sub_category_slug}','PublicPageController@showSubCat')->name('subcat.page');

Route::get('product/{category_slug}/{sub_category_slug}/total-cover','PublicPageController@totalCover')->name('totalcover.page');


//Route::get('/food-beverages/{subcategory_id}','PublicPageController@foodAndBeverages')->name('foodbeverages.page');

Route::get('hospitality','PublicPageController@hospitalityPage')->name('hospitality.page');

/*Route::get('/foodandproductrange','PublicPageController@foodAndProductRange')->name('foodandproductrange.page');*/



Route::get('product/{category_slug}/{sub_category_slug}/product-range','PublicPageController@productRange')->name('productrange.page');

Route::get('product/{category_slug}/{sub_category_slug}/equipment','PublicPageController@showEquipment')->name('equipment.page');

Route::get('product/{category_slug}/{sub_category_slug}/services','PublicPageController@showServices')->name('showServices.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training','PublicPageController@safetyTraining')->name('safety-training.page');

Route::get('product/{category_slug}/{sub_category_slug}/{product_range_slug}/productsds','PublicPageController@productSdsItems')->name('productsds.page');

Route::get('product/{category_slug}/{sub_category_slug}/{product_range_slug}/productsds/{product_slug}','PublicPageController@productInfo')->name('productInfo.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/chemical-training-safety','PublicPageController@chemicalTrainingSafety')->name('chemicaltrainingsafety.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/new-safety-initiatives','PublicPageController@newSafetyInitiatives')->name('newsafetyinitiatives.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/new-label','PublicPageController@newLabel')->name('newlabel.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/safety-and-operational-charts','PublicPageController@safetyOpCharts')->name('safetyOpCharts.page');

//Route::get('news','PublicPageController@newsPage')->name('news.page');

Route::get('contactus','PublicPageController@contactUsPage')->name('contactus.page');

//Route::get('aboutus','PublicPageController@aboutUsPage')->name('aboutus.page');
//
//Route::get('aboutus/ourvalues','PublicPageController@ourvaluesPage')->name('ourvalues.page');
//
//Route::get('aboutus/company-profile','PublicPageController@companyProfilePage')->name('company-profile.page');

Route::get('ourstory','PublicPageController@ourstoryPage')->name('ourstory.page');

Route::get('cleansafe-industrial-dispensing','PublicPageController@cleanSafeIndustrialPage')->name('cleansafe.page');

Route::get('services','PublicPageController@servicesPage')->name('services.page');

Route::get('service-report','PublicPageController@serviceReport')->name('servicesreport.page');





Route::get('search','PublicPageController@searchProduct')->name('searchProduct.page');


Route::get('/productinfopdf','ProductController@productInfoPdf')->name('productinfo.pdf');
//login
//Auth::routes();
/*Route::get('/home', 'HomeController@index')->name('home');*/


//Dashboard

Route::group(['prefix' => 'admin'], function() {


    Route::group(['middleware' => ['auth']], function() {

        Route::get('/','DashboardController@index');

        Route::get('/logout','LoginController@destroy')->name('logout.user');

        Route::resource('/dashboard','DashboardController');

        Route::resource('/pages','PageController');

        Route::resource('/categories','ProductCategoryController');

        Route::resource('/subcategories','ProductSubCategoryController');

        Route::resource('/productrange','ProductRangeController');

        Route::any('/productrange/index/productrangeData','ProductRangeController@productrangeData')->name('productrange.get');

        Route::resource('/products','ProductController');

        Route::any('/products/index/productsData','ProductController@productData')->name('products.get');

        Route::any('/products/index/deleteFile','ProductController@deleteImgDetails')->name('deleteFile.get');

    });

    Route::group(['middleware' => ['guest']], function() {

        Route::post('/login','Auth\LoginController@login');
        Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
        Route::post('/register','Auth\RegisterController@register');
        Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('register');

        //logout

    });

});

resources/views/cms/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Challenge Chemical Admin</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('theme-content/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">


    <!-- MetisMenu CSS -->
    <link href="{{ asset('theme-content/vendor/metisMenu/metisMenu.min.css') }}" rel="stylesheet">
    <!-- Custom CSS -->

    <link href="{{ asset('theme-content/dist/css/sb-admin-2.css') }}" rel="stylesheet">

    <!-- Morris Charts CSS -->
        @yield('page_css')

    <!-- Custom Fonts -->
    
    <link href="{{ asset('theme-content/vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        @include('cms.layouts.navbar-top')

        @include('cms.layouts.navbar-side')

        <div id="page-wrapper">
            @yield('content')
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    @yield('modal')

    <!-- jQuery -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script href="{{ asset('theme-content/vendor/bootstrap/js/bootstrap.min.js') }}"></script>

    <!-- Metis Menu Plugin JavaScript -->
   
    <script href="{{ asset('theme-content/vendor/metisMenu/metisMenu.min.js') }}"></script>

    @yield('page_js')

    <!-- Custom Theme JavaScript -->

    <script href="{{ asset('theme-content/dist/js/sb-admin-2.js') }}"></script>
    <script>

        $(document).ready(function() {
            $('[data-toggle="popover"]').popover({
                placement: 'top',
                trigger: 'hover'
            });
        });
    </script>
</body>

</html>

resources/views/cms/layouts/navbar-side.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                </div>
                <!-- /input-group -->
            </li>
            <li class="">
                <a href="{{route('dashboard.index')}}" class="{{ Request::is('admin') ? 'active' : '' }} {{ Request::is('admin/dashboard*') ? 'active' : '' }}" ><i class="fa fa-dashboard fa-fw "></i> Dashboard</a>
            </li>
            <li class="">
                {{--<a href="/admin/pages" class="{{ Request::is('admin/pages*') ? 'active' : '' }}" ><i class="fa fa-newspaper-o "></i> Product Pages</a>--}}
            </li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="{{route('products.index')}}"><i class="fa fa-files-o fa-fw"></i> Product<span class="fa arrow"></span></a>
                <style>
                    .menu-admin123 {
                        width:100%;
                        min-width: 160px;
                        box-shadow:none;
                        border:none;
                        background:none !important;
                    }
                    .menu-admin123 li a{
                        color:#4680b7 !important;
                    }
                    .dropdown .dropdown-menu {
                        -webkit-transition: all 0.3s;
                        -moz-transition: all 0.3s;
                        -ms-transition: all 0.3s;
                        -o-transition: all 0.3s;
                        transition: all 0.3s;

                        max-height: 0;
                        display: block;
                        overflow: hidden;
                        opacity: 0;
                    }

                    .dropdown.open .dropdown-menu {
                        max-height: 300px;
                        opacity: 1;
                    }
                </style>
                <ul class="nav nav-second-level dropdown-menu menu-admin123">
                    <li>
                        <a href="{{route('products.index')}}" class="{{ Request::is('admin/products*') ? 'active' : '' }}">Products</a>
                    </li>
                    <li>
                        <a href="{{route('productrange.index')}}" class="{{ Request::is('admin/productrange*') ? 'active' : '' }}">Product Range</a>
                    </li>
                    <li>
                        <a href="{{route('subcategories.index')}}" class="{{ Request::is('admin/subcategories*') ? 'active' : '' }}">Sub-categories</a>
                    </li>
                    <li>
                        <a href="{{route('categories.index')}}" class="{{ Request::is('admin/categories*') ? 'active' : '' }}">Categories</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->
</nav>

resources/views/cms/layouts/navbar-top.blade.php
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/admin">Challenge Chemical Admin</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        {{ Auth::user()->name }} <i class="fa fa-caret-down"> </i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        @guest
                            <li class="divider"></li>
                            <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Login</a>
                            </li>
                        @else
                            <li class="divider"></li>
                            <li><a href="{{route('logout.user')}}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                            </form>
                        @endguest
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->