routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
})->name('home');*/

Route::get('/','PublicPageController@index')->name('home');

Route::get('product/{category_slug}','PublicPageController@SubCatList')->name('category.page');

Route::get('products/{category_slug}','PublicPageController@landingPage')->name('landing.page');

Route::get('product/{category_slug}/{sub_category_slug}','PublicPageController@showSubCat')->name('subcat.page');

Route::get('product/{category_slug}/{sub_category_slug}/total-cover','PublicPageController@totalCover')->name('totalcover.page');


//Route::get('/food-beverages/{subcategory_id}','PublicPageController@foodAndBeverages')->name('foodbeverages.page');

Route::get('hospitality','PublicPageController@hospitalityPage')->name('hospitality.page');

/*Route::get('/foodandproductrange','PublicPageController@foodAndProductRange')->name('foodandproductrange.page');*/



Route::get('product/{category_slug}/{sub_category_slug}/product-range','PublicPageController@productRange')->name('productrange.page');

Route::get('product/{category_slug}/{sub_category_slug}/equipment','PublicPageController@showEquipment')->name('equipment.page');

Route::get('product/{category_slug}/{sub_category_slug}/services','PublicPageController@showServices')->name('showServices.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training','PublicPageController@safetyTraining')->name('safety-training.page');

Route::get('product/{category_slug}/{sub_category_slug}/{product_range_slug}/productsds','PublicPageController@productSdsItems')->name('productsds.page');

Route::get('product/{category_slug}/{sub_category_slug}/{product_range_slug}/productsds/{product_slug}','PublicPageController@productInfo')->name('productInfo.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/chemical-training-safety','PublicPageController@chemicalTrainingSafety')->name('chemicaltrainingsafety.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/new-safety-initiatives','PublicPageController@newSafetyInitiatives')->name('newsafetyinitiatives.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/new-label','PublicPageController@newLabel')->name('newlabel.page');

Route::get('product/{category_slug}/{sub_category_slug}/safety-training/safety-and-operational-charts','PublicPageController@safetyOpCharts')->name('safetyOpCharts.page');

//Route::get('news','PublicPageController@newsPage')->name('news.page');

Route::get('contactus','PublicPageController@contactUsPage')->name('contactus.page');

//Route::get('aboutus','PublicPageController@aboutUsPage')->name('aboutus.page');
//
//Route::get('aboutus/ourvalues','PublicPageController@ourvaluesPage')->name('ourvalues.page');
//
//Route::get('aboutus/company-profile','PublicPageController@companyProfilePage')->name('company-profile.page');

Route::get('ourstory','PublicPageController@ourstoryPage')->name('ourstory.page');

Route::get('cleansafe-industrial-dispensing','PublicPageController@cleanSafeIndustrialPage')->name('cleansafe.page');

Route::get('services','PublicPageController@servicesPage')->name('services.page');

Route::get('service-report','PublicPageController@serviceReport')->name('servicesreport.page');





Route::get('search','PublicPageController@searchProduct')->name('searchProduct.page');


Route::get('/productinfopdf','ProductController@productInfoPdf')->name('productinfo.pdf');
//login
//Auth::routes();
/*Route::get('/home', 'HomeController@index')->name('home');*/


//Dashboard

Route::group(['prefix' => 'admin'], function() {


    Route::group(['middleware' => ['auth']], function() {

        Route::get('/','DashboardController@index');

        Route::get('/logout','LoginController@destroy')->name('logout.user');

        Route::resource('/dashboard','DashboardController');

        Route::resource('/pages','PageController');

        Route::resource('/categories','ProductCategoryController');

        Route::resource('/subcategories','ProductSubCategoryController');

        Route::resource('/productrange','ProductRangeController');

        Route::any('/productrange/index/productrangeData','ProductRangeController@productrangeData')->name('productrange.get');

        Route::resource('/products','ProductController');

        Route::any('/products/index/productsData','ProductController@productData')->name('products.get');

        Route::any('/products/index/deleteFile','ProductController@deleteImgDetails')->name('deleteFile.get');

    });

    Route::group(['middleware' => ['guest']], function() {

        Route::post('/login','Auth\LoginController@login');
        Route::get('/login','Auth\LoginController@showLoginForm')->name('login');
        Route::post('/register','Auth\RegisterController@register');
        Route::get('/register','Auth\RegisterController@showRegistrationForm')->name('register');

        //logout

    });

});

resources/views/cms/categories/create.blade.php
@extends('cms.layouts.master')

@section('page_css')
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">Create category</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <legend>Category details</legend>
                    <form action="{{route('categories.store')}}" method="post" role="form" id="category-create-form">
                        {{ csrf_field() }}
                        <div class="form-group  {{ $errors->has('category_name') ? 'has-error' : '' }}">
                            <label for="">Category name</label>
                            <input type="text" class="form-control" name="category_name"  id=""  value="{{ old('category_name') }}" placeholder="Input category name">
                            {!! $errors->first('category_name', '<p class="help-block">:message</p>') !!}

                        </div>

                        <div class="form-group  {{ $errors->has('category_video') ? 'has-error' : '' }}">
                            <label for="">Category video link</label>
                            <input type="text" class="form-control" name="category_video"  id=""  value="{{ old('category_video') }}" placeholder="Input category video link">
                            {!! $errors->first('category_video', '<p class="help-block">:message</p>') !!}

                        </div>

                        <div class="form-group {{ $errors->has('category_description') ? 'has-error' : '' }}">
                            <label for="">Category Description</label>
                            <textarea type="text" class="form-control" name="category_description" id="description" value="{{ old('category_description') }}" placeholder="Input category description" style="resize:vertical;
height:200px;
min-height:200px;
max-height:200px;"></textarea>
                            {!! $errors->first('category_description', '<p class="help-block">:message</p>') !!}
                        </div>

                        <legend>Page details</legend>

                        <div class="form-group  {{ $errors->has('page_name') ? 'has-error' : '' }}">
                            <label for="">Page name / title</label>
                            <input type="text" class="form-control" name="page_name"  id=""  value="{{ old('page_name') }}" placeholder="Input page name">
                            {!! $errors->first('page_name', '<p class="help-block">:message</p>') !!}
                        </div>

                        <div class="form-group {{ $errors->has('page_content') ? 'has-error' : '' }}">
                            <label for="">Page Content</label>
                            <textarea type="text" class="form-control" name="page_content" id="description" value="{{ old('page_content') }}" placeholder="Input page content" style="resize:vertical;
height:200px;
min-height:200px;
max-height:200px;"></textarea>
                            {!! $errors->first('page_content', '<p class="help-block">:message</p>') !!}
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')

@endsection

@section('page_js')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CreateProductCategoryRequest','#category-create-form') !!}

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    {!! Toastr::message() !!}
@endsection

resources/views/cms/categories/edit.blade.php
@extends('cms.layouts.master')

@section('page_css')
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">Edit category</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <legend>Category details</legend>
                    <form action="{{route('categories.update',$product_category->id)}}" method="post" role="form" id="category-create-form">
                        {{method_field('PUT')}}
                        {{ csrf_field() }}
                        <div class="form-group  {{ $errors->has('category_name') ? 'has-error' : '' }}">
                            <label for="">Category name</label>
                            <input type="text" class="form-control" name="category_name"  id=""  value="{{$product_category->category_name}}" placeholder="Input category name">
                            <input type="hidden"  name="slug" value="{{$product_category->slug}}">
                            {!! $errors->first('category_name', '<p class="help-block">:message</p>') !!}
                        </div>

                        <div class="form-group  {{ $errors->has('category_video') ? 'has-error' : '' }}">
                            <label for="">Category video link</label>
                            <input type="text" class="form-control" name="category_video"  id=""  value="{{$product_category->category_video}}" placeholder="Input category video link">
                            {!! $errors->first('category_video', '<p class="help-block">:message</p>') !!}

                        </div>

                        <div class="form-group {{ $errors->has('category_description') ? 'has-error' : '' }}">
                            <label for="">Category Description</label>
                            <textarea type="text" class="form-control" name="category_description" id="description" placeholder="Input category description" style="resize:vertical;
height:200px;
min-height:200px;
max-height:200px;">{{$product_category->category_description}}</textarea>
                            {!! $errors->first('category_description', '<p class="help-block">:message</p>') !!}
                        </div>

                        <legend>Page details</legend>

                        <div class="form-group  {{ $errors->has('page_name') ? 'has-error' : '' }}">
                            <label for="">Page name / title</label>

                            <input type="text" class="form-control" name="page_name"  id=""  value="{{$product_category->page->page_name}}" placeholder="Input page name">
                            <input type="hidden"  name="slug_page" value="{{$product_category->page->slug}}">
                            {!! $errors->first('page_name', '<p class="help-block">:message</p>') !!}
                        </div>

                        <div class="form-group {{ $errors->has('page_content') ? 'has-error' : '' }}">
                            <label for="">Page Content</label>
                            <textarea type="text" class="form-control" name="page_content" id="description"  placeholder="Input page content" style="resize:vertical;height:200px;min-height:200px;max-height:200px;">{{$product_category->page->page_content}}</textarea>
                            {!! $errors->first('page_content', '<p class="help-block">:message</p>') !!}
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')

@endsection

@section('page_js')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    {!! JsValidator::formRequest('App\Http\Requests\CreateProductCategoryRequest','#category-create-form') !!}

    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    {!! Toastr::message() !!}
@endsection

resources/views/cms/categories/index.blade.php
@extends('cms.layouts.master')

@section('page_css')

@endsection

@section('content')
    <div class="row">
        @if ($errors->any())
            <div class="alert alert-danger">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        @endif
        <div class="col-lg-12">
            <h1 class="page-header">Categories
                {{--<a class="btn btn-primary" href="{{route('categories.create')}}"><i class="fa fa-plus"></i> Add category</a>--}}
            </h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Category data
                </div>

                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Category name</th>
                            <th>Created at</th>
                            <th>Options</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($pro_cat as $pc)
                            <tr>
                                <td>{{$pc->category_name}}</td>
                                <td>{{Carbon\Carbon::parse($pc->created_at)->format('d/m/Y')}}</td>
                                <td>
                                    <a href="{{route('categories.edit',$pc->id)}}" class="btn btn-info" role="button">Edit</a>{{-- | <a href="#" class="btn btn-danger" role="button">Delete</a>--}}
                                </td>
                            </tr>
                        @empty
                            no category available
                        @endforelse
                        </tbody>
                    </table>
                    {{ $pro_cat->links() }}
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

@section('modal')

@endsection

@section('page_js')

@endsection